### ISSUE TITLE
Post Selected Location to Backend API

### ISSUE THREAD

**Issue by brh55** [hopdrops/hopdrops#113]

**Comment by jasonwalsh** [comment]
Debugging notes:

- The API Gateway custom authorizer needs to have a TTL low. Even if AWS claims the authorizer token is not being cached, that does not appear to be the case.
- The `OPTIONS` request must *not* have an authorizer associated with it.
- The `Access-Control-Allow-Origin` header *must* include only one URL (e.g., `http://localhost:8080`)
