### ISSUE TITLE
Create a Route 53 alias record for the website hosted in S3

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#129]
**Describe the solution you'd like**
Currently, the static website hosted in S3 has a domain name automatically assigned by AWS. Create a Route 53 [alias record](https://aws.amazon.com/premiumsupport/knowledge-center/route-53-create-alias-records/) (e.g., `hopdrops.io`) that points to the website hosted in S3.

**Additional context**
Eventually we could create a CloudFront distribution (CDN) to serve the static content, but I don't think that's needed right now.

**Comment by AmillerSC** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
