### ISSUE TITLE
Handle failure for requesting OAuth access token

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#13]

**Comment by jasonwalsh** [comment]
@brh55 I believe we need another lambda function for this issue that can serve as the redirect URL for failures (e.g., `/v1/square/error`) or something similar.

**Comment by brh55** [comment]
@jasonwalsh @AmillerSC I think for MVP, just a static 400 and 404 page with basic text should suffice to accomplish our user goal. It won't hinder the user experience if it's not pretty, so I would wait for post MVP. In addition, I expect a low likelihood of the very first breweries to land on this page, as we will probably walk through on boarding with them.
