### ISSUE TITLE
Reorganize directory structure

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#20]
Below is a sample of the directory structure proposed for the repository:

```
.
└── square
    ├── functions
    │   ├── __init__.py
    │   ├── oauth.py
    │   └── oauth.tf
    ├── setup.py
    └── tests
        ├── __init__.py
        └── test_oauth.py

3 directories, 6 files
```

**Features**

- Both `*.py` and `*.tf` files exist in the `functions` subdirectory for easier integration testing using `terraform`
- The `tests` subdirectory contains test functions for unit testing lambda functions
- The `setup.py` file packages the lambda functions ending in `*.py` and installs dependencies required for testing (e.g, [`boto3`](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html))
- Tests can be invoked by running `python setup.py test`
- Code lints can be invoked by running `python setup.py lint`

Please comment with any questions or concerns.

**Comment by AmillerSC** [comment]
Does the inclusion of the Python scripts and Terraform files in a single directory create too much dependency/relationship on infrastructure an application? Just looking for a high-level understanding about any cons from this because the pros are clear (simplicity and interoperability).

Any issue with the setup.py NOT residing in the Functions folder? It's purpose seems related, so I ask.

As I understand it, we'll continue developing additional Terraform configurations (primarily for additional Lambda functions) to run Python scripts for future functionality. These both go under 'Functions.' I assume each TF/PY task will have an associated test (so 1:1 ratio?) If so, those go under 'Tests'

All of this is under 'Square.' Where are we storing the front-end stuff? What goes outside 'Square?'

Sorry for all the questions. Just want to be crystal clear. I appreciate the efforts.

**Comment by jasonwalsh** [comment]
> Does the inclusion of the Python scripts and Terraform files in a single directory create too much dependency/relationship on infrastructure an application?

Good question. I think the alternative would be to create a `terraform` subdirectory in the `functions` directory. Presumably, we'll be working in the `functions` directory, so the benefit of having the `*.tf` files in the same directory is that we can run `terraform apply` and not have to specify a target directory since Terraform assumes the `*.tf` exist in the working directory.

If we create a subdirectory `terraform` then we can simply run `terraform apply terraform` which seems kind of strange, but it *should* work.

> Any issue with the setup.py NOT residing in the Functions folder? It's purpose seems related, so I ask.

This structure replicates the design of a Python package. So in this example `square` is supposed to be a Python package, in which case, `setup.py` must exist in the root of the package.

Ideally, if we could add a subcommand to `python setup.py test` to run integration tests with Terraform, that would be preferred (e.g., python setup.py test terraform).

> I assume each TF/PY task will have an associated test (so 1:1 ratio?)

That's correct. Each lambda function (e.g., `*.py`) file will have an associated Terraform file (e.g., `*.tf`).

> If so, those go under 'Tests'

The `tests` directory contains unit tests for our lambda functions, meaning that we don't actually create infrastructure in AWS, but we verify that our lambda functions are behaving as expected and we're able to run them locally. Unit testing reduces the amount of time it takes for us to receive feedback if a test passed or failed because it doesn't have the overhead of creating infrastructure.

Integration tests will actually create the infrastructure and run end-to-end (e2e) tests (normally managed as a CI job, but can also be achieved locally running `terraform apply`).

> All of this is under 'Square.' Where are we storing the front-end stuff? What goes outside 'Square?'

All of the [React Native](https://facebook.github.io/react-native/) code will either exist in this repository or a separate repository. This question is probably better suited for @brh55.

**Comment by brh55** [comment]
> All of the [React Native](https://facebook.github.io/react-native/) code will either exist in this repository or a separate repository. This question is probably better suited for @brh55.

Yes to clarify, front-end stuff (the app) will be handled on a different repository. This will serve repo serves as the code related to the back-end services (vendor integrations, user management, authentication, notification services, etc).
