### ISSUE TITLE
Configure GPG signing key

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#28]
This repository requires commits to be signed using a GPG key.

**Instructions**

- [Generate](https://help.github.com/en/articles/generating-a-new-gpg-key) a new GPG key
- [Add](https://help.github.com/en/articles/adding-a-new-gpg-key-to-your-github-account) the GPG key to your GitHub account
- [Configure](https://help.github.com/en/articles/telling-git-about-your-signing-key) `git` to use the GPG key

- [x] @AmillerSC 
- [x] @brh55

**Comment by AmillerSC** [comment]
Added to Git bash and GitHub

**Comment by jasonwalsh** [comment]
@brh55 what is your progress with this?

**Comment by brh55** [comment]
I've had this, unsure why it's not reflected in my commits. Re-did it.
