### ISSUE TITLE
Define Merchant Schema for DynamoDB

### ISSUE THREAD

**Issue by brh55** [hopdrops/hopdrops#37]
**Things to account for:**
- Created Dated
- Updated Date
- Brewery Name
- Brewery Unique Identifier (GUID)
- `<Pos Vendor>` (Vendor)
- Active State
- Inventory State
- Can Release Information
- Active State

https://stackoverflow.com/questions/11101955/mongodb-schema-design-for-multiple-auth-user-accounts

**Comment by AmillerSC** [comment]
-Current Table::
		-Merchant ID
		-Access Token - Vendor Credentials
		-Refresh Token
		-Created Date
		-Updated Date
	-Future Table:
		-Created Date
		-Updated Date
		-State (Active or Inactive)
-Brewery Name
-Brewery Unique Identifier - Use GUID
		-Inventory State
		-Possible: ‘Vendor’ - Vendor PoS specification
