### ISSUE TITLE
Idempotent Brewery Registration

### ISSUE THREAD

**Issue by brh55** [hopdrops/hopdrops#38]
@jasonwalsh

**Comment by AmillerSC** [comment]
Expected to be implemented in redirect.py. @jasonwalsh will write tests first.

**Comment by AmillerSC** [comment]
No progress as of 08/15/19.

Value: No duplicate entries in DynamoDB table. 

Lookup on table to see if it exists; if it does then just redirect

**Comment by AmillerSC** [comment]
This is not actually an issue.

1. Cannot duplicate entry from AWS Web Console - "The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID xxxxxxxxxxxxxxxxxxxxxxxxx"

2. Testing with individual account; go to https://api.hopdrops.io/v1/square/oauth for first time and will be prompted to allow permissions. Then redirected. Sign out and visit link and prompted to login. When logging in, redirected (skipping permissions page) and no duplicate entry is created in the DynamoDB table.
