### ISSUE TITLE
Register CNAME for OAuth redirect URL

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#40]
The CNAME should be something like `api.hopdrops.com` which would also require a wildcard certificate.

/cc @AmillerSC

**Comment by AmillerSC** [comment]
1. Wildcard certificate created
2. Custom Domain Name created for API Gateway
3. Alias A record created for api.hopdrops.io to CloudFront URL

Redirect URL: https://api.hopdrops.io/v1/square/redirect
*Note: We will likely change the stages so this may change

**Comment by jasonwalsh** [comment]
Nice work on this
