### ISSUE TITLE
Apply pathing to API Gateway OAuth route

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#41]
`api.hopdrops.io/v1/square/oauth`

Where `v1` is the stage name of the API Gateway deployment and `square` is the parent resource.

**Comment by brh55** [comment]
@jasonwalsh Sorry scoots, I added it to the PR, I was half-way through completing it and figured I would finish it.

**Comment by jasonwalsh** [comment]
See #46
