### ISSUE TITLE
Include third-party dependencies in lambda runtime

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#45]
The `squareconnect` module is a dependency required by the `redirect` lambda function.

If the module does not exist, then Python raises an `ImportError`:

> Raised when the import statement has troubles trying to load a module. Also raised when the “from list” in from ... import has a name that cannot be found.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

**Comment by AmillerSC** [comment]
This issue depends on selection of Serverless or SAM. Both frameworks should include this functionality.
