### ISSUE TITLE
Configure API Gateway base path mapping in Terraform

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#46]
To use a [custom domain name](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) with API Gateway, a base mapping is required.

Terraform provides a [resource](https://www.terraform.io/docs/providers/aws/r/api_gateway_base_path_mapping.html) for managing a base mapping.

Assuming the domain name and certificate are not going to change, the base mapping _should_ be the only remaining resource required to manage in Terraform to finalize #42.

**Comment by AmillerSC** [comment]
New branch created 'Base-Map'

**Comment by AmillerSC** [comment]
TLS setting is not yet available in Terraform. Will be available when this PR is merged:
https://github.com/terraform-providers/terraform-provider-aws/pull/9128

**Comment by AmillerSC** [comment]
PR merged
