### ISSUE TITLE
GET Merchant Locations

### ISSUE THREAD

**Issue by brh55** [hopdrops/hopdrops#51]
The HTTP API shall include a `/locations` endpoint for manipulating (e.g., create, read, update, and destroy) merchant locations.

| Method | Endpoint |
| `GET` | `/locations` |

    $ curl https://api.hopdrops.io/v1/square/locations

**Comment by jasonwalsh** [comment]
@brh55 let me know if this design looks accurate to you. I'll also create the OAI schema.

**Comment by AmillerSC** [comment]
Removed other methods (PUT/POST/DELETE/etc.) as they are no longer relevant.
