### ISSUE TITLE
As a merchant, I want to specify a category to represent my can releases or new releases

### ISSUE THREAD

**Issue by brh55** [hopdrops/hopdrops#55]
In order to track only a specific set of items, the merchant can specify the category associated with a  can release.

## User End-Goal
The merchant should be able to type a category name that will show up on Square
![image.png](https://images.zenhubusercontent.com/5d066f858b88df5193f1f5fa/cf268836-7339-4f89-b448-0e06246111ea)

**Comment by AmillerSC** [comment]
This can be a merchant-provided category; otherwise we will create one automatically.

We will ask the merchant as an input field or drop down during on-boarding. If it is not defined, we will create.

**-Concern: If the merchant changes this, we need to be notified**
