### ISSUE TITLE
Location Endpoint (for React Mock Querying)

### ISSUE THREAD

**Issue by AmillerSC** [hopdrops/hopdrops#71]
Lambda function (get/locations)

This is in support of #57

**Comment by jasonwalsh** [comment]
If the JWT token is decoded successfully, then the `merchant_id` *should* be injected into the headers of the HTTP request (e.g., `X-Merchant-ID: C5MP1ZNT16XYR`).

### Flowchat

![Locations Flowchart](https://user-images.githubusercontent.com/2184329/64133221-b5342400-cda2-11e9-8c49-37ca39b5bae2.jpg)

**Comment by jasonwalsh** [comment]
@AmillerSC @brh55 let me know what you think of this workflow.

**Comment by jasonwalsh** [comment]
Actually, I think the header should be `X-Access-Token` which contains the access token *after* performing the lookup in the DynamoDB table.
