### ISSUE TITLE
Create Consolidated Deployment Command (Infrastructure)

### ISSUE THREAD

**Issue by AmillerSC** [hopdrops/hopdrops#77]
The Ansible playbook in PR #74 is lengthy but functional and greatly improves over the previous method (3 separate SAM commands).

We have two options as per @jasonwalsh:

1. Create a `Makefile` with targets that invokes the Ansible playbook
> 2. Create a [`setup.py`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) script with a [`cmdcls`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) directive for custom commands: (e.g., `python setup.py deploy`)

This is not currently a priority as of creation, but will be addressed when time permits.

**Comment by jasonwalsh** [comment]
484cb5b06269d8aa941780b3b29f61bbabeeaca8 resolves this by upgrading the AWS SAM CLI to use the `sam deploy` command.
