### ISSUE TITLE
Investigate persistent storage options

### ISSUE THREAD

**Issue by jasonwalsh** [hopdrops/hopdrops#9]

**Comment by AmillerSC** [comment]
Potential Options:
RDS
DynamoDB - Every Lambda functions includes Boto dependency
        -->Has API for easy integration
DocumentDB

AWS Secrets Manager? https://aws.amazon.com/secrets-manager/
        -->Probable scaling issues

**Comment by AmillerSC** [comment]
We have agreed on DynamoDB
